name: "spring-cities"
services:

  spring-cities-localstack:
    image: "localstack/localstack:3.5"
    container_name: "spring-cities-localstack"
    ports:
      - "4566:4566"
    environment:
      - "DEBUG=0"
      - "LS_LOG=info"
      - "SERVICES=dynamodb"
      - "EAGER_SERVICE_LOADING=1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../src/test/resources/localstack/table-data.json:/var/lib/localstack/table-data.json
      - ../../src/test/resources/localstack/table-setup.sh:/etc/localstack/init/ready.d/table-setup.sh
    networks:
      - "spring-cities-network"

networks:
  spring-cities-network: